pipeline:
  name: SecondPipeline
  identifier: SecondPipeline
  projectIdentifier: Default
  orgIdentifier: BrenttHarness0DemoOrgFME
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "help2"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
