pipeline:
  name: ProjPipelineWithOrgConnector
  identifier: ProjPipelineWithOrgConnector
  projectIdentifier: Default
  orgIdentifier: BrenttHarness0DemoOrgFME
  tags: {}
  stages:
    - stage:
        name: step1
        identifier: step1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
