pipeline:
  name: FME-Flag Pipeline
  identifier: FMEFlag_Pipeline
  projectIdentifier: ProjectFifteen
  orgIdentifier: BrenttsPersonalFME
  tags: {}
  stages:
    - stage:
        name: pull flag info
        identifier: pull_flag_info
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: FmeFlagUpdate
                  name: FmeFlagUpdate_1
                  identifier: FmeFlagUpdate_1
                  spec:
                    name: myFirstFlag
                    owners:
                      - Group:_fme_admins
        tags: {}
